//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VafinDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Product
    {
        public int Id { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> Product_count { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
